package com.tiny.mybatisgeneratordemo.gentry;

import java.io.Serializable;
import java.util.Date;

public class ClockRecord implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clock_record.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clock_record.clock_day
     *
     * @mbggenerated
     */
    private Date clockDay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clock_record.emp_no
     *
     * @mbggenerated
     */
    private Integer empNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clock_record.clock_time
     *
     * @mbggenerated
     */
    private Date clockTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clock_record.clock_type_code
     *
     * @mbggenerated
     */
    private Integer clockTypeCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clock_record.position
     *
     * @mbggenerated
     */
    private String position;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table clock_record
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clock_record.id
     *
     * @return the value of clock_record.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clock_record.id
     *
     * @param id the value for clock_record.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clock_record.clock_day
     *
     * @return the value of clock_record.clock_day
     *
     * @mbggenerated
     */
    public Date getClockDay() {
        return clockDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clock_record.clock_day
     *
     * @param clockDay the value for clock_record.clock_day
     *
     * @mbggenerated
     */
    public void setClockDay(Date clockDay) {
        this.clockDay = clockDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clock_record.emp_no
     *
     * @return the value of clock_record.emp_no
     *
     * @mbggenerated
     */
    public Integer getEmpNo() {
        return empNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clock_record.emp_no
     *
     * @param empNo the value for clock_record.emp_no
     *
     * @mbggenerated
     */
    public void setEmpNo(Integer empNo) {
        this.empNo = empNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clock_record.clock_time
     *
     * @return the value of clock_record.clock_time
     *
     * @mbggenerated
     */
    public Date getClockTime() {
        return clockTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clock_record.clock_time
     *
     * @param clockTime the value for clock_record.clock_time
     *
     * @mbggenerated
     */
    public void setClockTime(Date clockTime) {
        this.clockTime = clockTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clock_record.clock_type_code
     *
     * @return the value of clock_record.clock_type_code
     *
     * @mbggenerated
     */
    public Integer getClockTypeCode() {
        return clockTypeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clock_record.clock_type_code
     *
     * @param clockTypeCode the value for clock_record.clock_type_code
     *
     * @mbggenerated
     */
    public void setClockTypeCode(Integer clockTypeCode) {
        this.clockTypeCode = clockTypeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clock_record.position
     *
     * @return the value of clock_record.position
     *
     * @mbggenerated
     */
    public String getPosition() {
        return position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clock_record.position
     *
     * @param position the value for clock_record.position
     *
     * @mbggenerated
     */
    public void setPosition(String position) {
        this.position = position == null ? null : position.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clock_record
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", clockDay=").append(clockDay);
        sb.append(", empNo=").append(empNo);
        sb.append(", clockTime=").append(clockTime);
        sb.append(", clockTypeCode=").append(clockTypeCode);
        sb.append(", position=").append(position);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}