package com.tiny.mybatisgeneratordemo.gentry;

import java.io.Serializable;
import java.util.Date;

public class Schedule implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule.is_enabled
     *
     * @mbggenerated
     */
    private Byte isEnabled;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule.working_hours
     *
     * @mbggenerated
     */
    private Date workingHours;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule.earliest_working_hours
     *
     * @mbggenerated
     */
    private Date earliestWorkingHours;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule.lastest_working_hours
     *
     * @mbggenerated
     */
    private Date lastestWorkingHours;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule.off_hours
     *
     * @mbggenerated
     */
    private Date offHours;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule.earliest_off_hours
     *
     * @mbggenerated
     */
    private Date earliestOffHours;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule.lastest_off_hours
     *
     * @mbggenerated
     */
    private Date lastestOffHours;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table schedule
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule.id
     *
     * @return the value of schedule.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule.id
     *
     * @param id the value for schedule.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule.name
     *
     * @return the value of schedule.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule.name
     *
     * @param name the value for schedule.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule.is_enabled
     *
     * @return the value of schedule.is_enabled
     *
     * @mbggenerated
     */
    public Byte getIsEnabled() {
        return isEnabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule.is_enabled
     *
     * @param isEnabled the value for schedule.is_enabled
     *
     * @mbggenerated
     */
    public void setIsEnabled(Byte isEnabled) {
        this.isEnabled = isEnabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule.working_hours
     *
     * @return the value of schedule.working_hours
     *
     * @mbggenerated
     */
    public Date getWorkingHours() {
        return workingHours;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule.working_hours
     *
     * @param workingHours the value for schedule.working_hours
     *
     * @mbggenerated
     */
    public void setWorkingHours(Date workingHours) {
        this.workingHours = workingHours;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule.earliest_working_hours
     *
     * @return the value of schedule.earliest_working_hours
     *
     * @mbggenerated
     */
    public Date getEarliestWorkingHours() {
        return earliestWorkingHours;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule.earliest_working_hours
     *
     * @param earliestWorkingHours the value for schedule.earliest_working_hours
     *
     * @mbggenerated
     */
    public void setEarliestWorkingHours(Date earliestWorkingHours) {
        this.earliestWorkingHours = earliestWorkingHours;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule.lastest_working_hours
     *
     * @return the value of schedule.lastest_working_hours
     *
     * @mbggenerated
     */
    public Date getLastestWorkingHours() {
        return lastestWorkingHours;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule.lastest_working_hours
     *
     * @param lastestWorkingHours the value for schedule.lastest_working_hours
     *
     * @mbggenerated
     */
    public void setLastestWorkingHours(Date lastestWorkingHours) {
        this.lastestWorkingHours = lastestWorkingHours;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule.off_hours
     *
     * @return the value of schedule.off_hours
     *
     * @mbggenerated
     */
    public Date getOffHours() {
        return offHours;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule.off_hours
     *
     * @param offHours the value for schedule.off_hours
     *
     * @mbggenerated
     */
    public void setOffHours(Date offHours) {
        this.offHours = offHours;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule.earliest_off_hours
     *
     * @return the value of schedule.earliest_off_hours
     *
     * @mbggenerated
     */
    public Date getEarliestOffHours() {
        return earliestOffHours;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule.earliest_off_hours
     *
     * @param earliestOffHours the value for schedule.earliest_off_hours
     *
     * @mbggenerated
     */
    public void setEarliestOffHours(Date earliestOffHours) {
        this.earliestOffHours = earliestOffHours;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule.lastest_off_hours
     *
     * @return the value of schedule.lastest_off_hours
     *
     * @mbggenerated
     */
    public Date getLastestOffHours() {
        return lastestOffHours;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule.lastest_off_hours
     *
     * @param lastestOffHours the value for schedule.lastest_off_hours
     *
     * @mbggenerated
     */
    public void setLastestOffHours(Date lastestOffHours) {
        this.lastestOffHours = lastestOffHours;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", isEnabled=").append(isEnabled);
        sb.append(", workingHours=").append(workingHours);
        sb.append(", earliestWorkingHours=").append(earliestWorkingHours);
        sb.append(", lastestWorkingHours=").append(lastestWorkingHours);
        sb.append(", offHours=").append(offHours);
        sb.append(", earliestOffHours=").append(earliestOffHours);
        sb.append(", lastestOffHours=").append(lastestOffHours);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}