# server
server:
  port: 8084


spring:
  datasource:
    url: jdbc:mysql://localhost/brs_order?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: root


# mybatis config
mybatis:
  mapper-locations: classpath*:com/brs/order/mybatis/mapper/*.xml
  config-location: classpath:com/brs/order/mybatis/mybatis-config.xml
  # type-aliases-package: com.brs.oa.*.vo

# page plugin
pagehelper:
  # dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql