package com.tiny.mybatisgeneratordemo.gdao;

import com.tiny.mybatisgeneratordemo.gentry.ClockRecord;
import java.util.List;

public interface ClockRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clock_record
     *
     * @mbggenerated
     */
    int insert(ClockRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clock_record
     *
     * @mbggenerated
     */
    List<ClockRecord> selectAll();
}