package com.tiny.mybatisgeneratordemo.gdao;

import com.tiny.mybatisgeneratordemo.gentry.Schedule;
import java.util.List;

public interface ScheduleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule
     *
     * @mbggenerated
     */
    int insert(Schedule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule
     *
     * @mbggenerated
     */
    List<Schedule> selectAll();
}