# server
server:
  port: 8084



spring:
  datasource:
    url: jdbc:mysql://localhost/brs_idm?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: root
  redis:
    database: 0
    host: localhost
    password:
    port: 6379
    timeout: 5000ms
    lettuce:
      pool:
        max-wait:


# mybatis config
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  config-location: classpath:mybatis/mybatis-config.xml
  # type-aliases-package: com.brs.oa.*.vo

# page plugin
pagehelper:
  # dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql



#ldap配置信息，注意这里的userDn一定要写这种形式。referral设置为follow，连接AD时才需要配置
ldap:
  url: ldap://172.18.19.1:389
  userDn: CN=Administrator,CN=Users,DC=brs,DC=dev
  userPwd: Brs2017
  referral: follow
  domainName: '@brs.dev'
  base: OU=Onestep,DC=brs,DC=dev